hardware:
- site: 0
  device_name: genericuart
  settings:
    address: /dev/ttyUSB0
    baudrate: 9600
#TODO Stage separating
sequence:
- step_label: Send test command
  retry: 3
  device: genericuart
  timeout: 1000
  stepsettings:
      function: Send-Receive
      data: test
      threshold: test
- step_label: Send test command2
  retry: 3
  device: genericuart
  timeout: 1000
  stepsettings:
      function: Send-Receive
      data: test2
      threshold: test2
- step_label: Send test command3
  retry: 1000
  device: genericuart
  timeout: 1000
  stepsettings:
      function: Send-Receive
      data: test
      threshold: test3
